name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ["stable", "nightly", "v0.8.0"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Install dependencies
        run: |
          # Create a minimal Neovim config for testing
          mkdir -p ~/.config/nvim/pack/test/start

          # Install plenary.nvim for testing utilities
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim.git \
            ~/.config/nvim/pack/test/start/plenary.nvim

      - name: Run all tests
        run: |
          make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install stylua
        run: |
          # Install stylua for Lua formatting
          cargo install stylua --features lua52
        continue-on-error: true

      - name: Check formatting
        run: |
          if command -v stylua >/dev/null 2>&1; then
            stylua --check lua/ tests/
          else
            echo "stylua not available, skipping format check"
          fi
        continue-on-error: true

      - name: Run Luacheck (if available)
        run: |
          # Try to install luacheck for static analysis
          if command -v luarocks >/dev/null 2>&1; then
            luarocks install luacheck
            luacheck lua/ tests/
          else
            echo "luarocks not available, skipping luacheck"
          fi
        continue-on-error: true
